In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import numpy as np
np.random.seed(401)
import tensorflow as tf
tf.random.set_seed(401)
from sklearn.metrics import confusion_matrix, precision_score, recall_score, auc, roc_curve, roc_auc_score, f1_score

In [1]:
import hughes_data 
import argparse 
import pickle
import math

import random
random.seed(401)


In [2]:
import hughes_data

In [3]:
import hughes_castnet_main

[[[11.  3.  0. ...  1.  0.  0.]
  [ 8.  3.  0. ...  0.  0.  0.]
  [ 4.  1.  0. ...  0.  0.  0.]
  ...
  [ 2.  0.  1. ...  1.  0.  0.]
  [10.  3.  1. ...  0.  0.  0.]
  [ 6.  0.  1. ...  0.  0.  0.]]

 [[ 3.  1.  0. ...  0.  0.  0.]
  [ 1.  0.  1. ...  0.  0.  0.]
  [ 1.  1.  0. ...  0.  0.  0.]
  ...
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 2.  0.  1. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]

 [[ 2.  1.  0. ...  0.  0.  0.]
  [ 1.  0.  0. ...  0.  1.  0.]
  [ 1.  1.  0. ...  0.  0.  0.]
  ...
  [ 1.  0.  0. ...  0.  0.  0.]
  [ 2.  1.  1. ...  0.  0.  0.]
  [ 3.  0.  1. ...  0.  0.  0.]]

 ...

 [[24.  5.  8. ...  1.  1.  0.]
  [24.  4.  7. ...  0.  1.  0.]
  [21.  4.  5. ...  0.  1.  0.]
  ...
  [15.  0.  3. ...  0.  1.  1.]
  [19.  2.  6. ...  0.  1.  0.]
  [ 7.  1.  4. ...  0.  0.  0.]]

 [[16.  2.  1. ...  0.  1.  0.]
  [21.  3.  7. ...  0.  0.  0.]
  [10.  2.  2. ...  0.  0.  0.]
  ...
  [15.  4.  4. ...  0.  0.  0.]
  [17.  2.  8. ...  0.  0.  0.]
  [21.  2.  7. ...  0.  1.  

/Users/jyontika/Desktop/Python/github_hughes/opioid-overdose-models/CASTNet/hughes-CASTNet/hughes_castnet_model.py:70: UserWarning: `tf.nn.rnn_cell.BasicLSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  self.local_lstm_cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(self.HIDDEN_LAYER_SIZE)
/Users/jyontika/Desktop/Python/github_hughes/opioid-overdose-models/CASTNet/hughes-CASTNet/hughes_castnet_model.py:89: UserWarning: `tf.nn.rnn_cell.BasicLSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  global_lstm_cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(self.HIDDEN_LAYER_SIZE)


Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Iter: 1.0, total_loss: 3.205, regres_loss: 0.651, gl_loss: 0.661, ortho_loss: 1.893
Iter: 2.0, total_loss: 2.799, regres_loss: 0.289, gl_loss: 0.638, ortho_loss: 1.872
Iter: 3.0, total_loss: 2.673, regres_loss: 0.246, gl_loss: 0.612, ortho_loss: 1.815
Iter: 4.0, total_loss: 2.53, regres_loss: 0.251, gl_loss: 0.588, ortho_loss: 1.691
Epoch: 1, total_loss: 2.775, regres_loss: 0.352, gl_loss: 0.623, ortho_loss: 1.8
-----------------------------------------------------------------------------
Iter: 5.0, total_loss: 1.931, regres_loss: 0.18, gl_loss: 0.472, ortho_loss: 1.28
Iter: 6.0, total_loss: 2.191, regres_loss: 0.266, gl_loss: 0.539, ortho_loss: 1.386
Iter: 7.0, total_loss: 2.053, regres_loss: 0.271, gl_loss: 0.514, ortho_loss: 1.268
Iter: 8.0, total_loss: 1.915,

KeyboardInterrupt: 

In [4]:
hughes_castnet_main.castnet.results['loss']

NameError: name 'hughes_castnet_main' is not defined